### ISSUE TITLE
User Unit

### ISSUE THREAD

**Issue by andrewdunndev** [miles969/systemd-automount-template#1]
Can these work at user units? Seems like its more transportable to drop lines in /etc/fstab than drop many files into /etc/systemd/system.

**Comment by andrewdunndev** [comment]
is not possible.

**Comment by miles969** [comment]
you are right, that it seems to be equivalent to using fstab (there's little difference in copying lines to multiple fstab files compared to starting multiple units - at least in terms of actual typing), but i made these mainly because i wanted to "outsource" all the required network management and logging stuff to systemd. furthermore, i now make sure the files work on exactly one machine and i can be pretty confident they will work identically on another machine using systemd.

it comes down to a question of taste, i guess, but ive made far too many mistakes in fstab to trust myself to actually get the lines right every time...
